#!/bin/bash
RUNDIR=`pwd`

FILENAMES=( .ackrc .bashrc .gitconfig .screenrc .profile .bash_aliases )

for name in ${FILENAMES[@]}; do
    echo --- $name ---
    # Rename already exists file with old ext
    if [ -f $HOME/$name ]; then
        mv -v $HOME/$name $HOME/$name.old
    fi

    # Creat a symlink
    ln -sv $RUNDIR/$name $HOME/$name
done

echo DONE.


