#!/bin/bash
RUNDIR=`pwd`

FILENAMES=`find . -maxdepth 1 -type f | sed 's/\.\///' | grep -v '~'`
IGNORE_FILENAMES='TODO README.md deploy .git-completion.sh .git-prompt.sh .gitignore .DS_Store'

for name in ${FILENAMES[@]}; do
    echo --- $name ---

    # Ignore IGNORE_FILENAMES
    ignore_result=`echo $IGNORE_FILENAMES | grep $name`
    if [ -n "$ignore_result" ]; then
        echo "ignore IGNORE_FILENAME [$name]"
        continue
    fi

    # Rename already exists file with old ext
    dest=$HOME/$name
    if [ -e $dest ]; then
        ls_result=`ls -al $dest | grep "$RUNDIR/$name"`
        if [ ! -n "$ls_result" ]; then
            echo rename the file [$dest]
            mv -v $HOME/$name $HOME/$name.old
        else
            echo ignore dest[$dest]
            continue
        fi
    fi

    # Creat a symlink
    ln -sv $RUNDIR/$name $HOME/$name
done

echo DONE.


